# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='imageurl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
